### ISSUE TITLE
Support for FW 13.x.x.x

### ISSUE THREAD

**Issue by ghost** [zzerrg/gmfwtools#1]
There is a site, where it is described how to unpack and split (or at least mount) the filesystem of FW 13.0.0.90. This hint still works with actual version 13.0.0.99.
Maybe you can get an idea with this info on how to support 13.x files completely.

**Comment by ohinckel** [comment]
@sithyoda can you tell me where this site is? Can't find it with a short search.

**Comment by ohinckel** [comment]
I just added also support for FW 13.x.x.x - @sithyoda if you want you can test it now by using the code from PR #3.

**Comment by ghost** [comment]
Thx for the update. But in the meantime I have full telnet/ftp access to my device and I am able to change anything I want without flashing the whole /npc partition. I am also able to cross-compile c-code that runs on this platform. What I need would be someone who creates sw, e.g. a SIP client, for it.

**Comment by ohinckel** [comment]
OK, thanks for the feedback. I think @zzerrg can decide if this will be merged or not.

But can you tell me how to flash new firmwares on your devices? Can this be done directly on the devices (e.g. by `dd`ing the image file to the correct `mdblock` devices)? Or do you need to use a special software? Is this possible to flash using a Linux system? I'm interested in the flashing procedure.

**Comment by ghost** [comment]
I did not flash anything to my ip-doorbell which uses a 13.xx FW. It's basically a Hi3518E linux device (HiLinux). I just managed to get UART access (serial console) and then i started the already included "telnetd". Then you just telnet into the device and have a full embedded linux. The partition which can be flashed via app and tools is in fact the programm partition (in my case /npc), but this partition is r/w, so you can copy almost any programm there. The microsd-flashcard (/mnt/disc1) can also be used to copy programms easily to the device.

**Comment by zzerrg** [comment]
@ohinckel I've merged support for FW 13.x.x.x.

```
> python2 ./gmfwtools/gm_app_fw.py -v -f npcupg_13.00.01.10.bin
fw_ver : 13.00.01.10
jffs sz: 3069652
exec sz: 6599
csum   : c58b526d0f5518eb48f3d4ea0d1e9fab
sig ok : True
```
