### ISSUE TITLE
Support for 21.x.x.x Firmwares

### ISSUE THREAD

**Issue by hrch3k** [zzerrg/gmfwtools#6]
I have a yoosee camera based on gm8135. Been able to manualy flash it from terminal with flashcp command but have problems finding offsets. What can we do to add suport for 21.x.x.x versions so i can proper unpack/modify/pack the firmware?

**Comment by hrch3k** [comment]
I have successfully unpacked, mount, modify and flashed 21.xx.xx.xx versions firmware with DES from atc1441 post here https://github.com/zzerrg/gmfwtools/pull/5

21 : "\x9c\xae\x6a\x5a\xe1\xfc\xb0\x99" # specific for 21.0.0.x

just add it among the other DES keys in  gm_app_fw.py.

 

Cheers

**Comment by ohinckel** [comment]
Thanks for finding out the correct DES key, which I integrated in my PR #7.

I also updated the script to be able to:
* find keys in the npc binary
* brute force keys

Hopefully this will make it easier in the future to find the right keys for new firmware versions. For more details see PR #8.

**Comment by hrch3k** [comment]
Thanks to all of you guys that have made this tool! 

Did anybody had success with disabling the cloud services. ie. editing the npc binary?

**Comment by zzerrg** [comment]
@ohinckel Thank you for improving the tool :)

**Comment by zzerrg** [comment]
I've merged both PR #7 and #8
