### ISSUE TITLE
Support for 13.01.x.x FW

### ISSUE THREAD

**Issue by phpcoder** [zzerrg/gmfwtools#9]
Hi,
using gm_app_fw.py script for FW 13.01.x.x gives an error "Got unknown exec_sz = 0x%04x".
Tested versions are
13.01.00.06
13.01.00.43
13.01.00.91
Can support for 13.01.x.x be added?
Thank you for very useful tools.

**Comment by phpcoder** [comment]
For those interested, I modified the gm_app_fw.py and it works on 13.01.x.x without errors. 
EXEC_SZ is set to 0x1614 and DES_KEY to \x9c\xae\x6a\x5a\xe1\xfe\xb1\x89.
However, a packed binary is not successfully flashing from SD card. For v13 a fw binary should be named as "npcupg.bin".
I would appreciate any help on proper binary packing.

**Comment by zzerrg** [comment]
@phpcoder Thank you for the report. Going to add support of 13.01.x.x
p.s. It would be nice if you provide a link to 13.01.x.x FW image
